#ifdef SHOW_UNICODE
#define SHOW_LAM     "λ"
#define SHOW_TLAM    "Λ"
#define SHOW_ARROW   "→"
#define SHOW_FORALL  "∀"
#define SHOW_IN      "∈"
#define SHOW_NOT     "¬"
#define SHOW_TURN	 "⊢"
#define SHOW_ENV     "Γ"
#define SHOW_TENV    "Θ"
#else
#define SHOW_LAM     "\\"
#define SHOW_TLAM    "/\\"
#define SHOW_ARROW   "->"
#define SHOW_FORALL  "forall "
#define SHOW_IN      "in"
#define SHOW_NOT     "~"
#define SHOW_TURN	 "|-"
#define SHOW_ENV     "E"
#define SHOW_TENV    "TE"
#endif
